# Generated by Django 5.2.5 on 2025-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_turma_usuario_foto_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(blank=True, choices=[('aluno', 'Aluno'), ('cantineiro', 'Cantineiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='user_fotos/default.jpg', null=True, upload_to='user_fotos/'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
