# Generated by Django 5.2.5 on 2025-09-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_role_alter_usuario_foto_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('cantineiro', 'Cantineiro')], max_length=20),
        ),
    ]
