# Generated by Django 5.2.6 on 2025-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_foto_usuario_icone_alter_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='icone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/default.png', upload_to='fotos_perfil/'),
        ),
    ]
