# Generated by Django 5.2.5 on 2025-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
