# Generated by Django 5.2.5 on 2025-08-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_slug'),
        ('usuario', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.perfil'),
        ),
    ]
