# Generated by Django 5.2.5 on 2025-09-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produto_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='criado_por',
        ),
    ]
