# Generated by Django 5.2.6 on 2025-10-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão de Crédito/Débito'), ('pix', 'PIX')], default='dinheiro', max_length=20),
        ),
    ]
